<?php

namespace Urbicande\MiscBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BackgroundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BackgroundRepository extends EntityRepository
{
}
