<?php

namespace Urbicande\MiscBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MusiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MusiqueRepository extends EntityRepository
{
}
