<?php

namespace Urbicande\PersoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeRepository extends EntityRepository
{
  /**
   * Retourne tous les groupes d'un personnage
   * @param  int $memberId Id du personnage
   * @return Doctrine_Collection
   */
  public function getByMember($memberId)
  {
    $query = $this->createQueryBuilder('g');

    $query->leftJoin('g.members', 'm');

    $query->where('m.id = :member')
            ->setParameter('member', $memberId)
          ->orderBy('g.name', 'ASC');

    return $query->getQuery()->getResult();
  }
}
