<?php

namespace Urbicande\PersoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonnageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonnageRepository extends EntityRepository
{
  /**
   * Retourne tous les personnage d'un scénariste
   * @param  int $userId Id du scénariste
   * @return Doctrine_Collection
   */
  public function getByUser($userId)
  {
    $query = $this->createQueryBuilder('p');

    $query->leftJoin('p.writer', 'w');

    $query->where('w.id = :user')
          ->setParameter('user', $userId)
          ->orderBy('p.name', 'ASC');

    return $query->getQuery()->getResult();
  }

  /**
   * Compte le nombre de personnage par sexe
   * @return Array
   */
  public function countGender()
  {
    $em = $this->getEntityManager();
    $query = $em->createQuery('SELECT p.sex, COUNT(p.id) AS nb_sex FROM Urbicande\PersoBundle\Entity\Personnage p GROUP BY p.sex ORDER BY p.sex DESC');
    
    $query->useResultCache(true);
    $query->setResultCacheLifetime(3600);

    $results = $query->getResult();
    return $results;
  }

  /**
   * Compte le nombre de personnage par statut 
   * @return Array
   */
  public function countStatus()
  {
    $em = $this->getEntityManager();
    $query = $em->createQuery('SELECT p.status, COUNT(p.id) AS nb_status FROM Urbicande\PersoBundle\Entity\Personnage p GROUP BY p.status ORDER BY p.status DESC');
    
    $query->useResultCache(true);
    $query->setResultCacheLifetime(3600);

    $results = $query->getResult();
    return $results;
  }
}
