<?php

namespace Urbicande\PersoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RelationTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelationTypeRepository extends EntityRepository
{
}
