user_by_name:
    pattern:  /user/show/{username}
    defaults: { _controller: UrbicandeUserBundle:User:show }

user_list:
    pattern:  /user
    defaults: { _controller: UrbicandeUserBundle:User:index }

user_edit:
    pattern:  /user/edit
    defaults: { _controller: UrbicandeUserBundle:User:edit }

user_update:
    pattern:  /user/update
    defaults: { _controller: UrbicandeUserBundle:User:update }
    requirements: { _method: post }

size_update:
    pattern:  /user/update/size
    defaults: { _controller: UrbicandeHomeBundle:Home:saveResize }

order_update:
    pattern:  /user/update/order
    defaults: { _controller: UrbicandeHomeBundle:Home:saveOrder }