<?php

namespace Urbicande\ChronoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ScenoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScenoRepository extends EntityRepository
{
}
