<?php

namespace Urbicande\IntrigueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImplicationRepository extends EntityRepository
{
}
