<?php

namespace Urbicande\IntrigueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IntrigueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntrigueRepository extends EntityRepository
{ 
  /**
   * Retourne toutes les intrigues d'un scénariste
   * @param  int $userId Id du scénariste
   * @return Doctrine_Collection
   */
  public function getByUser($userId)
  {
    $query = $this->createQueryBuilder('i');

    $query->leftJoin('i.writer', 'w');

    $query->where('w.id = :user')
          ->setParameter('user', $userId)
          ->orderBy('i.name', 'ASC');

    return $query->getQuery()->getResult();
  }

  /**
   * Compte le nombre d'intrigue pour un perso et un type donné
   * @param  int $userId Id du scénariste
   * @return Doctrine_Collection
   */
  public function countByUserAndType($userName, $typeName)
  {
    $query = $this->createQueryBuilder('i');

    $query->leftJoin('i.type', 't');

    $query->where('w.id = :user')
          ->setParameter('user', $userId)
          ->orderBy('i.name', 'ASC');

    return $query->getQuery()->getResult();
  }
}
