<?php

namespace Urbicande\IntrigueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlotRepository extends EntityRepository
{
}
