# src/Urbicande/HomeBundle/Resources/config/routing.yml

Home:
    pattern:  /home
    defaults: { _controller: UrbicandeHomeBundle:Home:index }

log:
    pattern: /history
    defaults: { _controller: UrbicandeHomeBundle:Home:log }