background_list:
    pattern:  /background
    defaults: { _controller: UrbicandeMiscBundle:Background:index }

create_background:
    pattern:  /background/create
    defaults: { _controller: UrbicandeMiscBundle:Background:create }

background_edit:
    pattern:  /background/edit/{id}
    defaults: { _controller: UrbicandeMiscBundle:Background:edit }
    requirements:
      id:     \d+

background_revert:
    pattern:  /background/revert/{id}
    defaults: { _controller: UrbicandeMiscBundle:Background:revert }
    requirements:
      id:     \d+

background_delete:
    pattern:  /background/delete/{id}
    defaults: { _controller: UrbicandeMiscBundle:Background:delete }
    requirements:
      id:     \d+

background_update:
    pattern:  /background/update/{id}
    defaults: { _controller: "UrbicandeMiscBundle:Background:update" }
    requirements: { _method: post }
    requirements:
      id:     \d+

background_by_id:
    pattern:  /background/{id}
    defaults: { _controller: UrbicandeMiscBundle:Background:show }
    requirements:
      id:     \d+

download_background:
    pattern:  /background/download/{id}
    defaults: { _controller: UrbicandeMiscBundle:Background:generate }
    requirements:
      id:     \d+

stats:
    pattern:  /stats
    defaults: { _controller: UrbicandeMiscBundle:Stats:index }

musique_list:
    pattern:  /musique
    defaults: { _controller: UrbicandeMiscBundle:Musique:index }

create_musique:
    pattern:  /musique/create
    defaults: { _controller: UrbicandeMiscBundle:Musique:create }

musique_edit:
    pattern:  /musique/edit/{id}
    defaults: { _controller: UrbicandeMiscBundle:Musique:edit }
    requirements:
      id:     \d+

musique_revert:
    pattern:  /musique/revert/{id}
    defaults: { _controller: UrbicandeMiscBundle:Musique:revert }
    requirements:
      id:     \d+

musique_delete:
    pattern:  /musique/delete/{id}
    defaults: { _controller: UrbicandeMiscBundle:Musique:delete }
    requirements:
      id:     \d+

musique_update:
    pattern:  /musique/update/{id}
    defaults: { _controller: "UrbicandeMiscBundle:Musique:update" }
    requirements: { _method: post }
    requirements:
      id:     \d+

musique_by_id:
    pattern:  /musique/{id}
    defaults: { _controller: UrbicandeMiscBundle:Musique:show }
    requirements:
      id:     \d+

task_list:
    pattern:  /task
    defaults: { _controller: UrbicandeMiscBundle:Task:index }

create_task:
    pattern:  /task/create
    defaults: { _controller: UrbicandeMiscBundle:Task:create }

create_ajax_task:
    pattern:  /task/createAJAX
    defaults: { _controller: UrbicandeMiscBundle:Task:createAJAXTask }

task_edit:
    pattern:  /task/edit/{id}
    defaults: { _controller: UrbicandeMiscBundle:Task:edit }
    requirements:
      id:     \d+

task_revert:
    pattern:  /task/revert/{id}
    defaults: { _controller: UrbicandeMiscBundle:Task:revert }
    requirements:
      id:     \d+

task_delete:
    pattern:  /task/delete/{id}
    defaults: { _controller: UrbicandeMiscBundle:Task:delete }
    requirements:
      id:     \d+

task_update:
    pattern:  /task/update/{id}
    defaults: { _controller: "UrbicandeMiscBundle:Task:update" }
    requirements: { _method: post }
    requirements:
      id:     \d+

complete_task:
    pattern:  /task/complete/{id}
    defaults: { _controller: UrbicandeMiscBundle:Task:completeTask }
    requirements:
      id:     \d+

about:
    path: /about
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    UrbicandeMiscBundle:Static:about.html.twig
        maxAge:       86400
        sharedAge:    86400