parameters:
    urbicande.background_manager.class: Urbicande\MiscBundle\Manager\BackgroundManager
    urbicande.task_manager.class: Urbicande\MiscBundle\Manager\TaskManager
    urbicande.musique_manager.class: Urbicande\MiscBundle\Manager\MusiqueManager

services:
    urbicande.background_manager:
        class:     "%urbicande.background_manager.class%"
        arguments: ["@doctrine.orm.entity_manager"]
    urbicande.task_manager:
        class:     "%urbicande.task_manager.class%"
        arguments: ["@doctrine.orm.entity_manager"]
    urbicande.musique_manager:
        class:     "%urbicande.musique_manager.class%"
        arguments: ["@doctrine.orm.entity_manager"]
